package com.example.internship;

public class TODOLIST {
    //TODO
    //- ADD PROJECT - ADMIN ONLY - FLOATING ACTION - RECYCLER VIEW PROJECT
    //- ADD INTERN(REGISTER) - ADMIN ONLY - FLOATING ACTION - RECYCLER VIEW INTERN
    //- DETAIL PROJECT DATE START -> END
    //- REGEX REGISTER ONLY
    //- TOOLBAR - ISINYA ADA EDIT + DELETE
    //- FOTO INTERN!!!!!!!!!!!!!!
    //- PERFORMANCE INTERN
}
